#cloud-config

ssh_pwauth: false

users:
  - name: ${user}
    groups: wheel
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys: ${ssh_public_key}
  - name: ansible
    gecos: Ansible user
    groups: users,wheel
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys: ${ssh_public_key}

runcmd:
  - sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config
  - hostnamectl set-hostname ${hostname}
  # mount volume to /mnt/data
  - mkfs.ext4 /dev/sdb
  - mkdir -p /mnt/data
  - mount /dev/sdb /mnt/data
  - echo '/dev/sdb /mnt/data ext4 defaults,nofail 0 2' | sudo tee -a /etc/fstab
